awful.rules.rules = {
    -- All clients will match this rule.
    -- $ xprop | egrep -i 'class|name|role'
    -- http://awesome.naquadah.org/wiki/Understanding_Rules
    { rule = { },
      properties = { border_width = beautiful.border_width,
                     border_color = beautiful.border_normal,
                     focus = true,
                     keys = clientkeys,
                     buttons = clientbuttons } },
    { rule = { class = "MPlayer" }, properties = { floating = true } },
    { rule = { class = "mplayer2" }, properties = { floating = true } },
    { rule = { class = "Smplayer" }, properties = { floating = true } },
    { rule = { class = "Vlc" }, properties = { floating = true } },
    { rule = { class = "Stickynotes_applet" }, properties = { floating = true } },
    { rule = { class = "Topshelf.py" }, properties = { floating = true } },
    { rule = { class = "Display" }, properties = { floating = true } },
    { rule = { class = "Ipython" }, properties = { floating = true } },
    { rule = { class = "Pinentry" }, properties = { floating = true } },
    { rule = { class = "Stardict" }, properties = { floating = true } },
    { rule = { class = "Gimp" }, properties = { floating = true } },
    { rule = { class = "Gtklp" }, properties = { floating = true } },
    { rule = { class = "Qmv" }, properties = { floating = true } },
    { rule = { class = "Turpial" }, properties = { floating = true } },
    { rule = { class = "Foo" }, properties = { floating = true } },
    { rule = { class = "Deluge" }, properties = { floating = true } },
    { rule = { class = "GtkFoo" }, 
                properties = { floating = true,
                               tag = tags[1][1],
                               x=110,
                               y=100,
                               maximized_vertical = true,
                               maximized_horizontal = true
                              } 
             },
    { rule = { class = "Iceweasel" }, 
      except = { instance = "Navigator"},
      properties = {floating = true}
    },
    { rule = { class = "Stardict" }, properties = { floating = true } },
    { rule = { class = "Tilda" }, properties = { floating = true } },
    { rule = { class = "Yakuake" }, properties = { floating = true, border_width = 0 } },
    { rule = { class = "Guake" }, properties = { floating = true } },
    { rule = { class = "Wine" }, properties = { floating = true, border_color = "#d1940c" } },
    { rule = { class = "psi", }, properties = { floating = true } },
    { rule = { class="Psi-plus"}, properties = { floating = true } },
    { rule = { class = "kvm" }, properties = { floating = true } },
    { rule = { class = "MyPasswordSafe" }, properties = { floating = true } },
    { rule = { class = "Mssh" }, properties = { floating = true } },
    { rule = { class = "Krusader" }, properties = { floating = true } },
    { rule = { class = "f00" }, properties = { floating = true } },
    { rule = { class = " " }, properties = { floating = true } },
    { rule = { class = "Wpa_gui" }, properties = { floating = true } },
    { rule = { class = "URxvt" }, callback = awful.client.setslave },
    { rule = { class = "Gmrun" }, properties = { ontop = true } }
    -- Set Firefox to always map on tags number 2 of screen 1.
    -- { rule = { class = "Firefox" },
    --   properties = { tag = tags[1][2] } },
}
