#!/bin/zsh
# Soubor:  date.zsh
# Datum:   07.03.2019 16:09
# Autor:   Marek Nožka, marek <@T> tlapicka <dot> net
# Licence: GNU/GPL 
# Úloha:   datum i3wm
############################################################


#if [ -n $BLOCK_BUTTON ] && { [[ $BLOCK_BUTTON == 3 ]] || [[ $BLOCK_BUTTON == 1 ]]; }; then
if [ $BLOCK_BUTTON ]; then
    #xclock -update 1 >/dev/null &  # tohle se blokne a nechápu proč
    i3-msg -q 'exec xclock -update 1'
fi

date '+%_d. %b %Y %_H:%M'
date '+%_d.%_m. %_H:%M '

exit 0
